/**
 * Vendors the first-party Nuxt UI agent skill into `.agents/skills/nuxt-ui/`,
 * pinned to the @nuxt/ui version this project has installed.
 *
 *   pnpm skills:sync
 *
 * The skill is maintained by the Nuxt team (nuxt/ui repo, `skills/nuxt-ui/`).
 * It teaches an agent WHICH component to reach for and HOW to compose layouts;
 * it deliberately does not list props.
 *
 * Note: upstream's SKILL.md tells the agent to use the Nuxt UI MCP server for
 * props/slots. This template intentionally ships no MCP, so `.agents/skills/
 * nuxt-ui/PROJECT-OVERRIDE.md` redirects those lookups to node_modules and
 * .nuxt/ui, which are version-exact and cost far less context. CLAUDE.md
 * documents that route.
 */
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join, resolve } from 'node:path'
import process from 'node:process'
import { consola } from 'consola'

const REPO = 'nuxt/ui'
const SKILL_PREFIX = 'skills/nuxt-ui/'

/**
 * Skills live in `.agents/skills/` — the vendor-neutral Agent Skills location
 * (agentskills.io), NOT `.claude/skills/`. pi and OpenCode discover
 * `.agents/skills/` natively; Claude Code only looks in `.claude/skills/`, so
 * that path is a symlink to this one. Write through the real directory: a sync
 * that targeted the symlink would still work, but the repo would no longer say
 * which location is canonical.
 */
const OUT_DIR = resolve('.agents/skills/nuxt-ui')

interface TreeEntry { path: string, type: string }

/**
 * Upstream's SKILL.md opens with "use the Nuxt UI MCP server" and even gives
 * the `claude mcp add` command. An agent that activates this skill reads that
 * *before* it would ever open PROJECT-OVERRIDE.md, so the correction has to sit
 * at the top of the file the agent actually loads — not in a sibling it has no
 * reason to open. Injected on every sync so re-vendoring cannot undo it.
 *
 * Inserted after the YAML frontmatter, which must stay first for the skill to
 * be discovered at all.
 */
const GENERATED_HEADER
  = '<!-- GENERATED by `pnpm skills:sync` — DO NOT EDIT. '
    + 'The next sync overwrites this file; change scripts/skills-sync.ts instead. -->'

/**
 * Every vendored file gets a generated-file marker, not just SKILL.md.
 *
 * The `references/` pages are the ones an agent actually opens mid-task
 * (`recipes/forms.md`, `layouts/dashboard.md`), and they looked exactly like
 * hand-authored project docs — so an edit there is silently destroyed by the
 * next sync. The warning has to live where it is read.
 */
function markGenerated(body: string): string {
  const end = body.indexOf('\n---', 4)
  if (!body.startsWith('---') || end === -1) return `${GENERATED_HEADER}\n\n${body}`

  const cut = end + '\n---'.length
  return `${body.slice(0, cut)}\n\n${GENERATED_HEADER}\n${body.slice(cut)}`
}

function withProjectBanner(body: string): string {
  const banner = `
> **This project overrides one part of this skill.** It ships **no MCP server**,
> so ignore the "MCP Server" section below and every \`get_component\` /
> \`search_components\` instruction. Read component APIs from the installed
> package instead — version-exact and ~1/14th the context:
>
> - props, slots, events → \`node_modules/@nuxt/ui/dist/runtime/components/<Name>.vue.d.ts\`
> - allowed \`color\`/\`variant\`/\`size\` → \`.nuxt/ui/<name>.ts\`, first ~40 lines
>
> Everything else here — which component to use, how to compose it — applies as
> written. See \`PROJECT-OVERRIDE.md\` and the "Nuxt UI component APIs" section
> of \`CLAUDE.md\`.
`
  const end = body.indexOf('\n---', 4)
  if (!body.startsWith('---') || end === -1) {
    // No frontmatter to preserve — prepend and let the sync still succeed.
    return `${banner}\n${body}`
  }

  const cut = end + '\n---'.length
  return `${body.slice(0, cut)}\n${banner}${body.slice(cut)}`
}

async function main() {
  // Read from disk rather than require.resolve: @nuxt/ui does not expose
  // "./package.json" in its exports map. pnpm still symlinks the package
  // into node_modules, so this path is stable.
  const pkgRaw = await readFile(resolve('node_modules/@nuxt/ui/package.json'), 'utf8')
  const { version } = JSON.parse(pkgRaw) as { version: string }
  const tag = `v${version}`

  consola.start(`Syncing Nuxt UI skill from ${REPO}@${tag}`)

  const treeRes = await fetch(`https://api.github.com/repos/${REPO}/git/trees/${tag}?recursive=1`)
  if (!treeRes.ok) {
    throw new Error(`Could not read the ${tag} tree (HTTP ${treeRes.status}).`)
  }

  const { tree } = await treeRes.json() as { tree: TreeEntry[] }
  const files = tree
    .filter(t => t.type === 'blob' && t.path.startsWith(SKILL_PREFIX))
    .map(t => t.path)

  if (files.length === 0) throw new Error(`No files under ${SKILL_PREFIX} at ${tag}.`)

  // Fetch everything BEFORE deleting anything: a network failure half way
  // through would otherwise leave the skill directory wiped or partial, and
  // the agent reading it has no way to tell.
  const fetched = await Promise.all(files.map(async (path) => {
    const res = await fetch(`https://raw.githubusercontent.com/${REPO}/${tag}/${path}`)
    if (!res.ok) throw new Error(`Failed to fetch ${path} (HTTP ${res.status})`)
    return { path, body: await res.text() }
  }))

  await rm(OUT_DIR, { recursive: true, force: true })

  let bytes = 0
  await Promise.all(fetched.map(async ({ path, body }) => {
    bytes += Buffer.byteLength(body)

    const dest = join(OUT_DIR, path.slice(SKILL_PREFIX.length))
    await mkdir(dirname(dest), { recursive: true })

    // Mark first, then banner: withProjectBanner also inserts after the
    // frontmatter, so applying it last keeps the MCP correction at the very
    // top of the file — which is the whole point of injecting it.
    let out = body
    if (dest.endsWith('.md')) out = markGenerated(out)
    if (dest.endsWith('/SKILL.md')) out = withProjectBanner(out)

    await writeFile(dest, out, 'utf8')
  }))

  await writeFile(join(OUT_DIR, 'VERSION'), `${version}\n`)
  await writeFile(join(OUT_DIR, 'PROJECT-OVERRIDE.md'), `${GENERATED_HEADER}

# Project override — component API lookups

The upstream SKILL.md says to use the Nuxt UI MCP server for props, slots and
events. **This project ships no MCP server on purpose.** Use these instead —
both are version-exact for the installed @nuxt/ui (${version}) and far cheaper
in context than a docs page:

| You need | Read | Cost |
|---|---|---|
| Props, slots, events for \`<UButton>\` | \`node_modules/@nuxt/ui/dist/runtime/components/Button.vue.d.ts\` | ~500 tokens |
| Allowed \`color\`/\`variant\`/\`size\` values | \`.nuxt/ui/button.ts\` (top of file) | read the first ~40 lines |
| Which component to use, how to compose | \`SKILL.md\` + \`references/\` here | — |

The equivalent doc page on ui.nuxt.com is ~28 KB (~7K tokens) for a single
component, is not pinned to your installed version, and needs the network.

\`.nuxt/\` is generated — run \`pnpm nuxt prepare\` (or \`pnpm dev\`) if it's absent.
It also reflects your own \`app/app.config.ts\` theme overrides, which the
published docs cannot know about.
`)

  consola.success(
    `Vendored ${files.length} skill files (${(bytes / 1024).toFixed(0)} KB) for @nuxt/ui ${version} -> .agents/skills/nuxt-ui/`
  )
}

main().catch((error) => {
  consola.error(error instanceof Error ? error.message : error)
  process.exit(1)
})
